apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-deployment
  labels:
    name: todos-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: todos
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: todos
    spec:
      containers:
      - name: todos
        image: kylinhuang/todos_application:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
          name: todos-port       
        resources:
          requests:
            cpu: 125m