apiVersion: v1
kind: Service
metadata:
  name: todos-svc
  labels:
    name: todos-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: todos-port
  selector:
    name: todos